apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-vhosts
spec:
  rules:
  - host: apache.beisencorp.com
    http:
      paths:
      - backend:
          serviceName: apache-test
          servicePort: 80
  - host: nginx.beisencorp.com
    http:
      paths:
      - backend:
          serviceName: nginx-test
          servicePort: 80
